### ISSUE TITLE
Open Events Stream

### ISSUE THREAD

**Issue by fletchto99** [jkutianski/meetup-api#12]
Hey there,

Can you please support: http://www.meetup.com/meetup_api/docs/stream/2/open_events/

Also does this support the ability to send a mtime, so I can load the events since that mtime?

Regards,
Matt

**Comment by jkutianski** [comment]
Matt.
Stream Open Events don't use WS, that's the reason because this was not added before. I implemented chunked HTTP on https://github.com/jkutianski/meetup-api/commit/56369af8e2cfd51d9e9ccf87e95491880ecfc5e0 today, and here is the support for  `getStreamOpenEvents()` https://github.com/jkutianski/meetup-api/commit/2abb0b9a4cd9b8cb5920a17615716a210a933d0a.
Please tell me if you found any bug.

Juan Pablo

**Comment by fletchto99** [comment]
Awesome it's been working solid running 24/7 for 3 days now! Thanks a bucnh @jkutianski

**Comment by jkutianski** [comment]
@fletchto99 are you using this on the backend of pebble-meetup?

**Comment by fletchto99** [comment]
Yep! How did you know?

**Comment by jkutianski** [comment]
I saw your portfolio on http://fletchto99.com/. I want to start a page with applications that use this library.

**Comment by fletchto99** [comment]
Ah cool! Yeah sure go ahead an put mine down.

**Comment by jkutianski** [comment]
Can you send me a link of this app?

**Comment by fletchto99** [comment]
Here you go:

https://apps.getpebble.com/applications/5539d8fdbf1a59d7ac000053

**Comment by jkutianski** [comment]
Thanks! @fletchto99 
It's done!
https://github.com/jkutianski/meetup-api/wiki/Applications-using-this-library
